---
- name: Openscap Report
  hosts: all
  become: true
  vars:
    # ? This allows the ansible code to auto execute the generated remedies for your hosts: default: => { false }
    # ? will force the ansible to generate remedies and execute them, each playbook for eachs host.
    # ! THIS IS EXPERMENTAL, USE IT AT YOUR OWN RISK
    # ! Orverrides the autogenerate_ansible value
    auto_fix:
      false
      # ? This allows the ansible to autogenerate remedies for your hosts but not execute them: defult => { false }
      # ? WILL NOT EXECUTE ANY GENERATED PLAYBOOK, it's intended for create and fetch them use them by your self.
    autogenerate_ansible:
      false
      # ? This this is if you manually launch the remedies outside this playbook: default => { false }
      # ? In the case you execute them, just change this variable to true, and will only execute the post scan reports, and fetch the to your system
    only_post: false
  tasks:
    - name: Scan results post fix
      ansible.builtin.include_role:
        name: oscap_scan
      when: only_post
    - name: Set ansible distribution report - ROLE
      ansible.builtin.include_role:
        name: ansible_distribution_rhel
      when: ansible_distribution == "RedHat"
    - name: Setup Install oscap - ROLE
      ansible.builtin.include_role:
        name: setup_install
    - name: Copy policies - ROLE
      ansible.builtin.include_role:
        name: copy_policies
    - name: Scan vulnerabilities - ROLE
      ansible.builtin.include_role:
        name: oscap_scan
    - name: Autogenerate ansible fixes - ROLE
      ansible.builtin.include_role:
        name: oscap_generate_fix
      when: autogenerate_ansible
    - name: Fetch Autogenerated ansible fixes - ROLE
      ansible.builtin.include_role:
        name: fetch
        tasks_from: autofix.yml
      when: auto_fix
    - name: EXPERIMENTAL- Autofix vulnerabilities - ROLE - EXPERIMENTAL
      ansible.builtin.include_role:
        name: autofix
      when: auto_fix
    - name: Post Scan vulnerabilities
      ansible.builtin.include_role:
        name: oscap_scan
        tasks_from: post.yml
      when: auto_fix or only_post
    - name: Fetch reports
      ansible.builtin.include_role:
        name: fetch
