- name: Distribution name for RedHat hosts
  ansible.builtin.set_fact:
    ansible_distribution: "{{ ansible_distribution | lower | regex_replace('redhat', 'rhel') }}"
  when: ansible_distribution == "RedHat"
