name: ansible-lint
on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "stable", "release/v*", "docker_integration"]
tasks:
  - name: Perform integration testing with ansible-test
    uses: ansible-community/ansible-test-gh-action@release/v1
    with:
      ansible-core-version: stable-2.14
      pre-test-cmd: echo This runs before the ansible-test invocation
      target-python-version: 3.11
      controller-python-version: auto
      testing-type: integration
      test-deps: ansible.netcommon
  - name: Perform sanity testing with ansible-test
    uses: ansible-community/ansible-test-gh-action@release/v1
    with:
      ansible-core-version: stable-2.14
      testing-type: sanity
  - name: Perform unit testing with ansible-test
    uses: ansible-community/ansible-test-gh-action@release/v1
    with:
      ansible-core-version: stable-2.14
      pre-test-cmd: echo This runs before the ansible-test invocation
      target-python-version: 3.11
      testing-type: units
      test-deps: >-
        ansible.netcommon
        ansible.utils
